module.exports = {
  appKey: 'vtexappkey-pocicbcmall-QNVRIJ',
  appToken:
    'FEGQKCGROPMZOMLFUZSLURPBSNBEDRHIYLULVISVXMNJFNQAIBIWQWYOKZAKNXTHZNOPCTZYRWTFCANCDNLYDWSCJDTKYMDGVSCWMVMAPWIPZXPFTBEEIPNVSDKJBADU',
}
